export const ROUTES = {
  LOGIN: '/login',
  CHANGE_PASSWORD: '/change-password',
  HOME: '/',
  RECEIPT_LIST: '/receipts',
  RECEIPT_DETAIL: '/receiving/handovers/:handoverNo',
  RECEIPT_SCAN: '/receiving/handovers/:handoverNo/lines/:lineNo/scan',
  SCAN: '/scan',
  STOREKEEPER_CONFIRM: '/storekeeper-confirm',
  STOREKEEPER_CONFIRM_DETAIL: '/receiving/confirm/:handoverNo',
  PARTIAL_RECEIPT: '/partial-receipt',
  PARTIAL_RECEIPT_DETAIL: '/receiving/partial/:handoverNo',
  PACK360: '/pack360',
  REPACK: '/repack',
  DETACH_CARTONS: '/detach-cartons',
  PALLET: '/pallet',
  EXPORT: '/export',
  EXPORT_GATE: '/export-gate',
  PICKING: '/picking',
  MASTER_DATA: '/master-data',
  REPORTS: '/reports',
  LEDGER_REPORTS: '/ledger-reports',
  OEM_ORDERS: '/oem-orders',
  STOCK_MANAGEMENT: '/stock-management',
  ASSET_DOSSIER: '/trace/dossier',
  ADMIN_USERS: '/admin/users'
};
